const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),fs=require("fs"),path=require("path");
const app=express(),PORT=process.env.PORT||10000,SECRET=process.env.JWT_SECRET||"change-this-secret",DB=path.join(__dirname,"data","users.json");
app.use(cors());app.use(express.json({limit:"2mb"}));
const read=()=>{try{return JSON.parse(fs.readFileSync(DB,"utf8"))}catch{return[]}};const write=x=>{fs.mkdirSync(path.dirname(DB),{recursive:true});fs.writeFileSync(DB,JSON.stringify(x,null,2))};
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{res.status(401).json({error:"Unauthorized"})}}function admin(req,res,next){if(req.user?.role!=="admin")return res.status(403).json({error:"Admin only"});next()}
app.get("/api/health",(q,s)=>s.json({ok:true,service:"SnapScale API"}));
app.post("/api/auth/register",async(q,s)=>{let{name,email,password}=q.body;email=(email||"").trim().toLowerCase();if(!name||!email||!password||password.length<6)return s.status(400).json({error:"Name, email and 6+ character password required"});let u=read();if(u.some(x=>x.email===email))return s.status(409).json({error:"Email already registered"});let x={id:Date.now().toString(),name,email,password:await bcrypt.hash(password,12),role:"user",createdAt:new Date().toISOString()};u.push(x);write(u);s.status(201).json({token:jwt.sign({id:x.id,email:x.email,role:x.role},SECRET,{expiresIn:"30d"}),user:{name:x.name,email:x.email,role:x.role}})});
app.post("/api/auth/login",async(q,s)=>{let email=(q.body.email||"").trim().toLowerCase(),u=read().find(x=>x.email===email);if(!u||!(await bcrypt.compare(q.body.password||"",u.password)))return s.status(401).json({error:"Invalid email or password"});s.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},SECRET,{expiresIn:"30d"}),user:{name:u.name,email:u.email,role:u.role}})});
app.get("/api/me",auth,(q,s)=>{let u=read().find(x=>x.id===q.user.id);u?s.json({user:{name:u.name,email:u.email,role:u.role}}):s.status(404).json({error:"User not found"})});
app.get("/api/admin/users",auth,admin,(q,s)=>s.json(read().map(({password,...u})=>u)));
app.get("/api/admin/stats",auth,admin,(q,s)=>{let u=read();s.json({users:u.length,admins:u.filter(x=>x.role==="admin").length})});
let users=read(),ae=(process.env.ADMIN_EMAIL||"admin@snapscale.app").toLowerCase();if(!users.some(x=>x.email===ae)){users.push({id:"admin",name:"SnapScale Admin",email:ae,password:bcrypt.hashSync(process.env.ADMIN_PASSWORD||"ChangeMe123!",12),role:"admin",createdAt:new Date().toISOString()});write(users)}
app.use(express.static(path.join(__dirname,"public")));app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("SnapScale server on "+PORT));